"""Initial migration

Revision ID: c4d2c52d50a8
Revises: 
Create Date: 2025-08-13 10:07:10.074663+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4d2c52d50a8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_asin'), 'price_history', ['asin'], unique=False)
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_timestamp'), 'price_history', ['timestamp'], unique=False)
    op.create_table('product_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.Column('conversions', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Float(), nullable=True),
    sa.Column('bounce_rate', sa.Float(), nullable=True),
    sa.Column('avg_session_duration', sa.Float(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_analytics_asin'), 'product_analytics', ['asin'], unique=False)
    op.create_index(op.f('ix_product_analytics_date'), 'product_analytics', ['date'], unique=False)
    op.create_index(op.f('ix_product_analytics_id'), 'product_analytics', ['id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('product_url', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_asin'), 'products', ['asin'], unique=True)
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_index(op.f('ix_products_asin'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_product_analytics_id'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_date'), table_name='product_analytics')
    op.drop_index(op.f('ix_product_analytics_asin'), table_name='product_analytics')
    op.drop_table('product_analytics')
    op.drop_index(op.f('ix_price_history_timestamp'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_asin'), table_name='price_history')
    op.drop_table('price_history')
    # ### end Alembic commands ###